Repository fcpkata/catalog, pull requests merged in 2020-07, with the labels that each got.

#1 Updated deployment settings
  .classpath
  .gitignore
  .project
  Dockerfile
  OWNERS
  OWNERS_ALIASES
  charts/catalog/values.yaml
  src/main/resources/application.properties
Labels: approved, lgtm, size/L

#2 Updated existing endpoint to return products based on category
  charts/catalog/values.yaml
  src/main/java/com/spring/catalog/controller/CatalogController.java
  src/main/java/com/spring/catalog/controller/ProductService.java
  src/main/java/com/spring/catalog/model/Category.java
  src/main/java/com/spring/catalog/model/Price.java
  src/main/java/com/spring/catalog/model/Product.java
  src/main/java/com/spring/catalog/util/ProductUtility.java
  src/main/resources/application.properties
  src/test/java/com/spring/catalog/controller/CatalogControllerTest.java
  src/test/java/com/spring/controller/acceptance/CatalogAcceptanceTest.java
Labels: approved, lgtm, size/L

#4 Created new end point for get details of single product
  .settings/org.eclipse.jdt.core.prefs
  src/main/java/com/spring/catalog/controller/CatalogController.java
  src/main/java/com/spring/catalog/model/Product.java
  src/main/java/com/spring/catalog/util/ProductUtility.java
  src/test/java/com/spring/catalog/controller/CatalogControllerTest.java
  src/test/java/com/spring/controller/acceptance/CatalogAcceptanceTest.java
Labels: approved, lgtm, size/L

#5 Refactored the code to make Service Independent
  src/main/java/com/spring/catalog/CatalogConfiguration.java
  src/main/java/com/spring/catalog/controller/CatalogController.java
  src/main/java/com/spring/catalog/controller/ProductService.java
  src/main/java/com/spring/catalog/model/BookCategory.java
  src/main/java/com/spring/catalog/model/Category.java
  src/main/java/com/spring/catalog/model/ElectronicsCategory.java
  src/main/java/com/spring/catalog/model/Product.java
  src/main/java/com/spring/catalog/repository/MockRepository.java
  src/main/java/com/spring/catalog/repository/Repository.java
  src/main/java/com/spring/catalog/util/ProductUtility.java
  src/test/java/com/spring/catalog/controller/CatalogControllerSpec.java
  src/test/java/com/spring/catalog/controller/CatalogControllerTest.java
  src/test/java/com/spring/catalog/service/ProductServiceSpec.java
  src/test/java/com/spring/controller/acceptance/CatalogAcceptanceTest.java
Labels: approved, lgtm, size/L

#6 add filter functionality
  src/main/java/com/spring/catalog/controller/CatalogController.java
  src/main/java/com/spring/catalog/controller/ProductService.java
  src/main/java/com/spring/catalog/util/ProductUtility.java
  src/test/java/com/spring/catalog/controller/CatalogControllerSpec.java
  src/test/java/com/spring/catalog/service/ProductServiceSpec.java
  src/test/java/com/spring/controller/acceptance/CatalogAcceptanceTest.java
Labels: approved, size/L

#7 Add filter with category for products
  src/main/java/com/spring/catalog/controller/CatalogController.java
  src/main/java/com/spring/catalog/controller/ProductService.java
  src/test/java/com/spring/catalog/controller/CatalogControllerSpec.java
  src/test/java/com/spring/catalog/service/ProductServiceSpec.java
  src/test/java/com/spring/controller/acceptance/CatalogAcceptanceTest.java
Labels: approved, lgtm, size/M

#8 Add capability to filter products by category & genre
  .classpath
  src/main/java/com/spring/catalog/CatalogConfiguration.java
  src/main/java/com/spring/catalog/controller/CatalogController.java
  src/main/java/com/spring/catalog/controller/ProductService.java
  src/main/java/com/spring/catalog/exception/ProductNotFoundException.java
  src/main/java/com/spring/catalog/model/BookCategory.java
  src/main/java/com/spring/catalog/model/Category.java
  src/main/java/com/spring/catalog/model/ElectronicsCategory.java
  src/main/java/com/spring/catalog/model/FilterCriteria.java
  src/main/java/com/spring/catalog/model/Price.java
  src/main/java/com/spring/catalog/model/Product.java
  src/main/java/com/spring/catalog/model/ProductMetadata.java
  src/main/java/com/spring/catalog/repository/CategoryRepository.java
  src/main/java/com/spring/catalog/repository/MockProductRepository.java
  src/main/java/com/spring/catalog/repository/MockRepository.java
  src/main/java/com/spring/catalog/repository/ProductRepository.java
  src/main/java/com/spring/catalog/service/CatalogService.java
  src/main/java/com/spring/catalog/util/ProductUtility.java
  src/test/java/com/spring/catalog/controller/CatalogControllerSpec.java
  src/test/java/com/spring/catalog/controller/CatalogControllerTest.java
  src/test/java/com/spring/catalog/model/ProductMetadataTest.java
  src/test/java/com/spring/catalog/service/ProductServiceSpec.java
  src/test/java/com/spring/controller/acceptance/CatalogAcceptanceTest.java
  src/test/java/com/spring/controller/service/CatalogServiceTest.java
Labels: approved, lgtm, size/XXL

#10 Catalog acceptance fix
  src/main/java/com/spring/catalog/controller/CatalogController.java
  src/main/java/com/spring/catalog/controller/advice/ControllerExceptionHandler.java
  src/main/java/com/spring/catalog/exception/ProductNotFoundException.java
  src/main/java/com/spring/catalog/model/FilterCriteria.java
  src/main/java/com/spring/catalog/model/Price.java
  src/main/java/com/spring/catalog/model/Product.java
  src/main/java/com/spring/catalog/model/ProductMetadata.java
  src/main/java/com/spring/catalog/repository/MockProductRepository.java
  src/main/java/com/spring/catalog/service/CatalogService.java
  src/test/java/com/spring/catalog/controller/CatalogControllerTest.java
  src/test/java/com/spring/catalog/model/ProductTest.java
  src/test/java/com/spring/controller/acceptance/GetProductDetailsAcceptanceTest.java
  src/test/java/com/spring/controller/acceptance/GetProductsAcceptanceTest.java
  src/test/java/com/spring/controller/service/CatalogServiceTest.java
Labels: approved, lgtm, size/XL

#12 Added Actuator dependency
  build.gradle
  charts/catalog/values.yaml
  src/main/java/com/spring/catalog/controller/CatalogController.java
  src/main/resources/application.properties
  src/test/java/com/spring/controller/acceptance/GetProductDetailsAcceptanceTest.java
  src/test/java/com/spring/controller/acceptance/GetProductsAcceptanceTest.java
Labels: approved, lgtm, size/S

#13 Added logic to display Least Price change
  .settings/org.eclipse.core.resources.prefs
  charts/catalog/values.yaml
  charts/preview/requirements.yaml
  src/main/java/com/spring/catalog/CatalogConfiguration.java
  src/main/java/com/spring/catalog/model/Item.java
  src/main/java/com/spring/catalog/model/Product.java
  src/main/java/com/spring/catalog/model/ProductInformation.java
  src/main/java/com/spring/catalog/model/ProductInformations.java
  src/main/java/com/spring/catalog/model/Seller.java
  src/main/java/com/spring/catalog/repository/MockProductRepository.java
  src/main/java/com/spring/catalog/service/CatalogService.java
  src/main/java/com/spring/catalog/service/InventoryService.java
  src/main/java/com/spring/catalog/service/ProductInventoryService.java
  src/test/java/com/spring/catalog/service/CatalogServiceTest.java
  src/test/java/com/spring/catalog/service/ProductInventoryServiceTest.java
  src/test/java/com/spring/controller/acceptance/GetProductDetailsAcceptanceTest.java
  src/test/java/com/spring/controller/acceptance/GetProductsAcceptanceTest.java
  src/test/java/com/spring/controller/service/CatalogServiceTest.java
Labels: approved, lgtm, size/XL

#14 Added Shipping charges service
  src/main/java/com/spring/catalog/CatalogConfiguration.java
  src/main/java/com/spring/catalog/service/CatalogService.java
  src/test/java/com/spring/catalog/controller/CatalogControllerTest.java
  src/test/java/com/spring/catalog/service/CatalogServiceTest.java
Labels: approved, size/S
